import { SystemMessage, HumanMessage } from "@langchain/core/messages";
import {
  CompanyStateType,
  AgentEvent,
  CodeGenMode,
  ProjectItem,
} from "../state.js";
import { getModel } from "../state.js";
import { parseAgentResponse } from "./utils/utils.js";
import { writeProjectFiles, createZipArchive } from "../generators/index.js";

const FALLBACK_FILES = [
  { path: "package.json", content: "{\n  \"name\": \"generated-project\",\n  \"version\": \"1.0.0\",\n  \"type\": \"module\",\n  \"scripts\": {\n    \"dev\": \"tsx watch src/index.ts\",\n    \"build\": \"tsc\",\n    \"start\": \"node dist/index.js\"\n  },\n  \"dependencies\": {},\n  \"devDependencies\": {\n    \"typescript\": \"^5.0.0\",\n    \"tsx\": \"^4.21.0\",\n    \"@types/node\": \"^20.0.0\"\n  }\n}\n" },
  { path: "tsconfig.json", content: "{\n  \"compilerOptions\": {\n    \"target\": \"ES2022\",\n    \"module\": \"NodeNext\",\n    \"moduleResolution\": \"NodeNext\",\n    \"outDir\": \"dist\",\n    \"rootDir\": \"src\",\n    \"strict\": true,\n    \"esModuleInterop\": true\n  },\n  \"include\": [\"src\"]\n}\n" },
  { path: "src/index.ts", content: "// Generated entry point\nconsole.log(\"Hello from generated project!\");\n" },
  { path: "README.md", content: "# Generated Project\n\nGenerated by A-Company AI.\n\n## Setup\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n" },
];

export interface CodeGenInput {
  project_id: string;
  project_title: string;
  project_description: string;
  tech_stack: string[];
  implementation_plan: string[];
  code_structure: string;
  wireframes: string[];
  design_system: string;
  dependencies: string[];
  mode: CodeGenMode;
}

export async function codeGeneratorAgent(
  state: CompanyStateType,
  emit: (event: AgentEvent) => void,
  input: CodeGenInput
) {
  const { project_id, project_title, project_description, tech_stack, implementation_plan, code_structure, wireframes, design_system, dependencies, mode } = input;

  emit({
    agent: "code_generator",
    phase: "quality",
    status: "started",
    message: `Code Generator starting: ${mode} mode for "${project_title}"`,
    timestamp: Date.now(),
  });

  emit({
    agent: "code_generator",
    phase: "quality",
    status: "thinking",
    message: "Generating full project file manifest...",
    timestamp: Date.now(),
  });

  const model = getModel(0.2, 8192);

  const systemPrompt = `You are an expert full-stack software engineer. Generate a complete, production-quality, runnable project as a JSON array of file objects.

CRITICAL: Output ONLY a valid JSON array. No prose, no markdown, no code fences. Start with [ and end with ].
Format: [{"path": "relative/path/file.ext", "content": "full file content here"}, ...]

Requirements:
- Paths relative to project root, no leading slash
- TypeScript everywhere
- All imports use correct relative paths
- package.json: include ALL dependencies + scripts: dev/build/start/test
- .env.example: every env var referenced in code
- Code must be syntactically correct, complete, runnable — NO placeholders, NO "// TODO", NO stub functions
- README.md: project title, description, setup steps (npm install && npm run dev), env vars

File structure (monolith):
  package.json, tsconfig.json, .env.example, README.md
  src/index.ts (entry point — boots the server/app)
  src/routes/ (one file per resource)
  src/models/ (data models / schemas)
  src/services/ (business logic)
  src/middleware/ (auth, validation, error handling)
  src/types/ (shared TypeScript interfaces)
  If it is a web app / landing page: also include src/public/index.html + src/public/styles.css with real HTML/CSS content

File structure (monorepo):
  package.json (workspaces), tsconfig.json, .env.example, README.md
  packages/api/ — same as monolith src/
  packages/web/ — full React/Vite frontend with src/App.tsx, src/main.tsx, index.html, vite.config.ts
  packages/shared/ — shared types and utilities

Generate at least 8 meaningful files with real, working implementation code. If the project is a landing page or website, generate real HTML with semantic markup, CSS with proper styles, and any required JS.`;


  const humanMessage = `Project: ${project_title}
Description: ${project_description}
Tech Stack: ${tech_stack.join(", ")}
Implementation Plan: ${implementation_plan.join(" | ")}
Code Structure: ${code_structure}
Wireframes: ${wireframes.join(" | ")}
Design System: ${design_system}
Dependencies: ${dependencies.join(", ")}
Mode: ${mode}`;

  const response = await model.invoke([
    new SystemMessage(systemPrompt),
    new HumanMessage(humanMessage),
  ]);

  const usage = response.usage_metadata as { input_tokens?: number; output_tokens?: number } ?? {};
  emit({
    agent: "code_generator",
    phase: "quality",
    status: "token_usage",
    message: `Tokens: ${usage.input_tokens ?? 0} in / ${usage.output_tokens ?? 0} out`,
    timestamp: Date.now(),
    token_usage: { input_tokens: usage.input_tokens ?? 0, output_tokens: usage.output_tokens ?? 0 },
  });

  const raw = (response.content as string).trim();

  let files: Array<{ path: string; content: string }>;
  try {
    const parsed = parseAgentResponse(raw);
    if (!Array.isArray(parsed)) {
      throw new Error("Response is not an array");
    }
    files = (parsed as Array<{ path: string; content: string }>).filter(
      (f) => typeof f.path === "string" && typeof f.content === "string"
    );
    if (files.length === 0) {
      console.warn("[CodeGenerator] Empty manifest, using fallback files");
      files = FALLBACK_FILES;
    }
  } catch (e) {
    console.warn("[CodeGenerator] Parse failed, using fallback:", e instanceof Error ? e.message : String(e));
    files = FALLBACK_FILES;
  }

  // Write files to disk
  const baseDir = "./generated";
  try {
    await writeProjectFiles(project_id, files, baseDir);
    emit({
      agent: "code_generator",
      phase: "quality",
      status: "thinking",
      message: `Wrote ${files.length} files to disk`,
      timestamp: Date.now(),
    });
  } catch (e) {
    console.error("[CodeGenerator] File write failed:", e);
    throw e;
  }

  // Create zip archive
  let zipPath: string;
  try {
    zipPath = await createZipArchive(project_id, files, baseDir);
    emit({
      agent: "code_generator",
      phase: "quality",
      status: "done",
      message: `Zip created: ${zipPath} (${files.length} files)`,
      timestamp: Date.now(),
    });
  } catch (e) {
    console.error("[CodeGenerator] Zip creation failed:", e);
    throw e;
  }

  return {
    current_project: {
      generated_code: {
        generated_at: Date.now(),
        mode,
        file_count: files.length,
        zip_path: zipPath,
      },
    } as ProjectItem,
    agent_events: [
      {
        agent: "code_generator" as const,
        phase: "quality" as const,
        status: "done" as const,
        message: `Generated ${files.length} files in ${mode} mode`,
        timestamp: Date.now(),
      },
    ],
  };
}