import { SystemMessage, HumanMessage } from "@langchain/core/messages";
import {
  CompanyStateType,
  AgentEvent,
  CodeGenMode,
  ProjectItem,
} from "../state.js";
import { getModel } from "../state.js";
import { parseAgentResponse } from "./utils/utils.js";
import { writeProjectFiles, createZipArchive } from "../generators/index.js";

function parseDelimiterFormat(raw: string): Array<{ path: string; content: string }> {
  const files: Array<{ path: string; content: string }> = [];

  // Strip think blocks and markdown fences LLMs commonly add
  let cleaned = raw
    .replace(/<think>[\s\S]*?<\/think>/g, "")
    .replace(/^```[\w]*\r?\n?/gm, "")
    .replace(/^```\s*$/gm, "");

  // Allow optional whitespace/newline before ===END===
  const pattern = /===FILE:\s*([^\n]+?)\s*===\r?\n([\s\S]*?)===END===\s*/g;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(cleaned)) !== null) {
    const filePath = match[1].trim();
    const content = match[2];
    if (filePath) files.push({ path: filePath, content });
  }
  return files;
}

const FALLBACK_FILES = [
  { path: "package.json", content: "{\n  \"name\": \"generated-project\",\n  \"version\": \"1.0.0\",\n  \"type\": \"module\",\n  \"scripts\": {\n    \"dev\": \"tsx watch src/index.ts\",\n    \"build\": \"tsc\",\n    \"start\": \"node dist/index.js\"\n  },\n  \"dependencies\": {},\n  \"devDependencies\": {\n    \"typescript\": \"^5.0.0\",\n    \"tsx\": \"^4.21.0\",\n    \"@types/node\": \"^20.0.0\"\n  }\n}\n" },
  { path: "tsconfig.json", content: "{\n  \"compilerOptions\": {\n    \"target\": \"ES2022\",\n    \"module\": \"NodeNext\",\n    \"moduleResolution\": \"NodeNext\",\n    \"outDir\": \"dist\",\n    \"rootDir\": \"src\",\n    \"strict\": true,\n    \"esModuleInterop\": true\n  },\n  \"include\": [\"src\"]\n}\n" },
  { path: "src/index.ts", content: "// Generated entry point\nconsole.log(\"Hello from generated project!\");\n" },
  { path: "README.md", content: "# Generated Project\n\nGenerated by Happy-Agents AI.\n\n## Setup\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n" },
];

export interface CodeGenInput {
  project_id: string;
  project_title: string;
  project_description: string;
  tech_stack: string[];
  implementation_plan: string[];
  code_structure: string;
  wireframes: string[];
  design_system: string;
  dependencies: string[];
  mode: CodeGenMode;
}

export async function codeGeneratorAgent(
  state: CompanyStateType,
  emit: (event: AgentEvent) => void,
  input: CodeGenInput
) {
  const { project_id, project_title, project_description, tech_stack, implementation_plan, code_structure, wireframes, design_system, dependencies, mode } = input;

  emit({
    agent: "code_generator",
    phase: "quality",
    status: "started",
    message: `Code Generator starting: ${mode} mode for "${project_title}"`,
    timestamp: Date.now(),
  });

  emit({
    agent: "code_generator",
    phase: "quality",
    status: "thinking",
    message: "Generating full project file manifest...",
    timestamp: Date.now(),
  });

  const model = getModel(0.2, 16000);

  const systemPrompt = `You are an expert full-stack software engineer. Generate a complete, production-quality, runnable project using the EXACT format below.

OUTPUT FORMAT — follow precisely, no deviations:

===FILE: relative/path/to/file.ext===
full file content goes here
(may span multiple lines)
===END===

===FILE: another/file.ext===
...content...
===END===

Rules:
- Use this delimiter format ONLY. No JSON, no prose, no markdown outside file blocks.
- Paths are relative to project root, no leading slash.
- TypeScript everywhere (except HTML/CSS/JSON config files).
- All imports must use correct relative paths.
- package.json: include ALL runtime and dev dependencies, scripts: dev/build/start/test.
- .env.example: list every env var the code reads.
- Code must be syntactically correct, complete, runnable — NO placeholders, NO "// TODO", NO stub functions.
- README.md: title, description, setup steps, env var list.

Required files for MONOLITH mode:
  package.json
  tsconfig.json
  .env.example
  README.md
  src/index.ts            (entry — boots server/app)
  src/routes/index.ts     (route definitions)
  src/services/           (business logic, one file per domain)
  src/middleware/         (auth, error handling, validation)
  src/types/index.ts      (shared TypeScript interfaces)
  For web/landing page projects: src/public/index.html + src/public/styles.css with real, complete HTML and CSS

Required files for MONOREPO mode:
  package.json            (workspaces config)
  tsconfig.json
  .env.example
  README.md
  packages/api/package.json
  packages/api/src/index.ts
  packages/api/src/routes/index.ts
  packages/web/package.json
  packages/web/vite.config.ts
  packages/web/index.html
  packages/web/src/main.tsx
  packages/web/src/App.tsx
  packages/shared/src/types.ts

Generate at minimum 10 meaningful files with real implementation. Every file must contain working code that matches the project requirements.`;



  const humanMessage = `Project: ${project_title}
Description: ${project_description}
Tech Stack: ${tech_stack.join(", ")}
Implementation Plan: ${implementation_plan.join(" | ")}
Code Structure: ${code_structure}
Wireframes: ${wireframes.join(" | ")}
Design System: ${design_system}
Dependencies: ${dependencies.join(", ")}
Mode: ${mode}`;

  const response = await model.invoke([
    new SystemMessage(systemPrompt),
    new HumanMessage(humanMessage),
  ]);

  const usage = response.usage_metadata as { input_tokens?: number; output_tokens?: number } ?? {};
  emit({
    agent: "code_generator",
    phase: "quality",
    status: "token_usage",
    message: `Tokens: ${usage.input_tokens ?? 0} in / ${usage.output_tokens ?? 0} out`,
    timestamp: Date.now(),
    token_usage: { input_tokens: usage.input_tokens ?? 0, output_tokens: usage.output_tokens ?? 0 },
  });

  const raw = (response.content as string).trim();

  let files: Array<{ path: string; content: string }>;

  // Primary: delimiter format — immune to JSON encoding issues in file content
  const delimiterFiles = parseDelimiterFormat(raw);
  if (delimiterFiles.length >= 3) {
    files = delimiterFiles;
  } else {
    console.warn(`[CodeGenerator] Delimiter parser got ${delimiterFiles.length} files. Raw preview (first 500 chars):\n${raw.slice(0, 500)}`);
    // Fallback: try JSON (handles responses that still use JSON format)
    try {
      const parsed = parseAgentResponse(raw);
      if (!Array.isArray(parsed)) throw new Error("not array");
      const jsonFiles = (parsed as Array<{ path: string; content: string }>).filter(
        (f) => typeof f.path === "string" && typeof f.content === "string"
      );
      if (jsonFiles.length >= 3) {
        files = jsonFiles;
      } else {
        console.warn("[CodeGenerator] Both parsers yielded <3 files, using fallback");
        files = FALLBACK_FILES;
      }
    } catch (e) {
      console.warn("[CodeGenerator] Parse failed, using fallback:", e instanceof Error ? e.message : String(e));
      files = FALLBACK_FILES;
    }
  }

  // Write files to disk
  const baseDir = "./generated";
  try {
    await writeProjectFiles(project_id, files, baseDir);
    emit({
      agent: "code_generator",
      phase: "quality",
      status: "thinking",
      message: `Wrote ${files.length} files to disk`,
      timestamp: Date.now(),
    });
  } catch (e) {
    console.error("[CodeGenerator] File write failed:", e);
    throw e;
  }

  // Create zip archive
  let zipPath: string;
  try {
    zipPath = await createZipArchive(project_id, files, baseDir);
    emit({
      agent: "code_generator",
      phase: "quality",
      status: "done",
      message: `Zip created: ${zipPath} (${files.length} files)`,
      timestamp: Date.now(),
    });
  } catch (e) {
    console.error("[CodeGenerator] Zip creation failed:", e);
    throw e;
  }

  return {
    current_project: {
      generated_code: {
        generated_at: Date.now(),
        mode,
        file_count: files.length,
        zip_path: zipPath,
      },
    } as ProjectItem,
    agent_events: [
      {
        agent: "code_generator" as const,
        phase: "quality" as const,
        status: "done" as const,
        message: `Generated ${files.length} files in ${mode} mode`,
        timestamp: Date.now(),
      },
    ],
  };
}