import { SystemMessage, HumanMessage } from "@langchain/core/messages";
import {
  CompanyStateType,
  AgentEvent,
  CodeGenMode,
  ProjectItem,
} from "../state.js";
import { getModel } from "../state.js";
import { parseAgentResponse } from "./utils/utils.js";
import { writeProjectFiles, createZipArchive } from "../generators/index.js";

const FALLBACK_FILES = [
  { path: "package.json", content: "{\n  \"name\": \"generated-project\",\n  \"version\": \"1.0.0\",\n  \"type\": \"module\",\n  \"scripts\": {\n    \"dev\": \"tsx watch src/index.ts\",\n    \"build\": \"tsc\",\n    \"start\": \"node dist/index.js\"\n  },\n  \"dependencies\": {},\n  \"devDependencies\": {\n    \"typescript\": \"^5.0.0\",\n    \"tsx\": \"^4.21.0\",\n    \"@types/node\": \"^20.0.0\"\n  }\n}\n" },
  { path: "tsconfig.json", content: "{\n  \"compilerOptions\": {\n    \"target\": \"ES2022\",\n    \"module\": \"NodeNext\",\n    \"moduleResolution\": \"NodeNext\",\n    \"outDir\": \"dist\",\n    \"rootDir\": \"src\",\n    \"strict\": true,\n    \"esModuleInterop\": true\n  },\n  \"include\": [\"src\"]\n}\n" },
  { path: "src/index.ts", content: "// Generated entry point\nconsole.log(\"Hello from generated project!\");\n" },
  { path: "README.md", content: "# Generated Project\n\nGenerated by A-Company AI.\n\n## Setup\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n" },
];

export interface CodeGenInput {
  project_id: string;
  project_title: string;
  project_description: string;
  tech_stack: string[];
  implementation_plan: string[];
  code_structure: string;
  wireframes: string[];
  design_system: string;
  dependencies: string[];
  mode: CodeGenMode;
}

export async function codeGeneratorAgent(
  state: CompanyStateType,
  emit: (event: AgentEvent) => void,
  input: CodeGenInput
) {
  const { project_id, project_title, project_description, tech_stack, implementation_plan, code_structure, wireframes, design_system, dependencies, mode } = input;

  emit({
    agent: "code_generator",
    phase: "quality",
    status: "started",
    message: `Code Generator starting: ${mode} mode for "${project_title}"`,
    timestamp: Date.now(),
  });

  emit({
    agent: "code_generator",
    phase: "quality",
    status: "thinking",
    message: "Generating full project file manifest...",
    timestamp: Date.now(),
  });

  const model = getModel(0.2);

  const systemPrompt = `You are an expert full-stack software engineer. Generate a complete, runnable project as a JSON array of file objects.

Rules:
- Output ONLY valid JSON array: [{"path": "relative/path/file.ts", "content": "..."}, ...]
- Paths must be relative to project root, no leading slash
- Include ALL necessary files: package.json, tsconfig.json, src/index.ts, src/routes/*.ts, src/models/*.ts, src/services/*.ts, src/middleware/*.ts, .env.example, README.md, etc.
- TypeScript is always used
- All imports must use correct relative paths within the generated structure
- For package.json: include ALL dependencies from the input (merged with standard deps), scripts: dev/build/start
- For .env.example: include all env vars referenced in the code
- code must be syntactically correct, complete, and runnable
- README.md must include: project title, setup instructions (npm install && npm run dev)
- NEVER use placeholder comments like "// TODO: implement" — provide actual logic
- Max 50 files total

For monorepo mode: include workspace package.json at root + packages/api, packages/web, packages/shared
For monolith mode: single package.json at root with all deps and src/ containing everything`;

  const humanMessage = `Project: ${project_title}
Description: ${project_description}
Tech Stack: ${tech_stack.join(", ")}
Implementation Plan: ${implementation_plan.join(" | ")}
Code Structure: ${code_structure}
Wireframes: ${wireframes.join(" | ")}
Design System: ${design_system}
Dependencies: ${dependencies.join(", ")}
Mode: ${mode}`;

  const response = await model.invoke([
    new SystemMessage(systemPrompt),
    new HumanMessage(humanMessage),
  ]);

  const usage = response.usage_metadata as { input_tokens?: number; output_tokens?: number } ?? {};
  emit({
    agent: "code_generator",
    phase: "quality",
    status: "token_usage",
    message: `Tokens: ${usage.input_tokens ?? 0} in / ${usage.output_tokens ?? 0} out`,
    timestamp: Date.now(),
    token_usage: { input_tokens: usage.input_tokens ?? 0, output_tokens: usage.output_tokens ?? 0 },
  });

  const raw = (response.content as string).trim();

  let files: Array<{ path: string; content: string }>;
  try {
    const parsed = parseAgentResponse(raw);
    if (!Array.isArray(parsed)) {
      throw new Error("Response is not an array");
    }
    files = (parsed as Array<{ path: string; content: string }>).filter(
      (f) => typeof f.path === "string" && typeof f.content === "string"
    );
    if (files.length === 0) {
      console.warn("[CodeGenerator] Empty manifest, using fallback files");
      files = FALLBACK_FILES;
    }
  } catch (e) {
    console.warn("[CodeGenerator] Parse failed, using fallback:", e instanceof Error ? e.message : String(e));
    files = FALLBACK_FILES;
  }

  // Write files to disk
  const baseDir = "./generated";
  try {
    await writeProjectFiles(project_id, files, baseDir);
    emit({
      agent: "code_generator",
      phase: "quality",
      status: "thinking",
      message: `Wrote ${files.length} files to disk`,
      timestamp: Date.now(),
    });
  } catch (e) {
    console.error("[CodeGenerator] File write failed:", e);
    throw e;
  }

  // Create zip archive
  let zipPath: string;
  try {
    zipPath = await createZipArchive(project_id, files, baseDir);
    emit({
      agent: "code_generator",
      phase: "quality",
      status: "done",
      message: `Zip created: ${zipPath} (${files.length} files)`,
      timestamp: Date.now(),
    });
  } catch (e) {
    console.error("[CodeGenerator] Zip creation failed:", e);
    throw e;
  }

  return {
    current_project: {
      generated_code: {
        generated_at: Date.now(),
        mode,
        file_count: files.length,
        zip_path: zipPath,
      },
    } as ProjectItem,
    agent_events: [
      {
        agent: "code_generator" as const,
        phase: "quality" as const,
        status: "done" as const,
        message: `Generated ${files.length} files in ${mode} mode`,
        timestamp: Date.now(),
      },
    ],
  };
}