import { SystemMessage, HumanMessage } from "@langchain/core/messages";
import { CompanyStateType, AgentEvent, ProjectItem } from "../state.js";
import { getModel } from "../state.js";
import { parseAgentResponse } from "./utils/utils.js";
import { writeProjectFiles } from "../generators/index.js";

export interface DesignGenInput {
  project_id: string;
  project_title: string;
  project_description: string;
  wireframes: string[];
  design_system: string;
}

export async function designGeneratorAgent(
  state: CompanyStateType,
  emit: (event: AgentEvent) => void,
  input: DesignGenInput
) {
  const { project_id, project_title, project_description, wireframes, design_system } = input;

  emit({
    agent: "design_generator",
    phase: "execution",
    status: "started",
    message: `Design Generator starting for "${project_title}"`,
    timestamp: Date.now(),
  });

  emit({
    agent: "design_generator",
    phase: "execution",
    status: "thinking",
    message: "Analyzing wireframes and design system...",
    timestamp: Date.now(),
  });

  const model = getModel(0.3);

  const systemPrompt = `You are an expert UI/UX designer. Generate HTML/CSS design files from wireframes and design system specs.

Output ONLY a valid JSON array of file objects:
[{"path": "relative/path/file.html", "content": "..."}, ...]

Rules:
- Output ONLY valid JSON array: [{"path": "relative/path/file.html", "content": "..."}, ...]
- Paths must be relative to project root, no leading slash
- Generate index.html, assets/css/styles.css, assets/js/main.js, and any supporting files
- Use the design system colors, typography, and spacing rules
- Wireframes describe layout and component structure — translate to semantic HTML + CSS
- Include responsive design (mobile-first)
- All CSS must be inline in <style> tags or in separate CSS file
- All JS must be inline in <script> tags or in separate JS file
- Max 20 files total
- NO external CDN dependencies — all assets generated locally`;

  const humanMessage = `Project: ${project_title}
Description: ${project_description}
Wireframes: ${wireframes.join("\n---\n")}
Design System: ${design_system}`;

  const response = await model.invoke([
    new SystemMessage(systemPrompt),
    new HumanMessage(humanMessage),
  ]);

  const usage = response.usage_metadata as { input_tokens?: number; output_tokens?: number } ?? {};
  emit({
    agent: "design_generator",
    phase: "execution",
    status: "token_usage",
    message: `Tokens: ${usage.input_tokens ?? 0} in / ${usage.output_tokens ?? 0} out`,
    timestamp: Date.now(),
    token_usage: { input_tokens: usage.input_tokens ?? 0, output_tokens: usage.output_tokens ?? 0 },
  });

  const raw = (response.content as string).trim();
  console.log("[DesignGenerator] raw LLM response length:", raw.length);

  let files: Array<{ path: string; content: string }>;
  try {
    const parsed = parseAgentResponse(raw);
    if (!Array.isArray(parsed)) {
      throw new Error("Response is not an array");
    }
    files = (parsed as Array<{ path: string; content: string }>).filter(
      (f) => typeof f.path === "string" && typeof f.content === "string"
    );
    if (files.length === 0) {
      throw new Error("Empty manifest after filtering");
    }
  } catch (e) {
    console.warn("[DesignGenerator] Parse failed, using fallback:", e instanceof Error ? e.message : String(e));
    files = [
      { path: "index.html", content: `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>${project_title}</title>\n  <style>body { font-family: system-ui; padding: 2rem; }</style>\n</head>\n<body>\n  <h1>${project_title}</h1>\n  <p>${project_description}</p>\n</body>\n</html>` },
      { path: "README.md", content: `# Generated Design\n\nGenerated by A-Company AI Design Generator.\n\n## Files\n- index.html — main HTML page\n- assets/css/styles.css — styles\n- assets/js/main.js — JavaScript\n` },
    ];
  }

  // Write files to disk
  const baseDir = "./generated-designs";
  try {
    await writeProjectFiles(project_id, files, baseDir);
    emit({
      agent: "design_generator",
      phase: "execution",
      status: "thinking",
      message: `Wrote ${files.length} design files to disk`,
      timestamp: Date.now(),
    });
  } catch (e) {
    console.error("[DesignGenerator] File write failed:", e);
    throw e;
  }

  const outputPath = `${baseDir}/${project_id}`;

  emit({
    agent: "design_generator",
    phase: "execution",
    status: "done",
    message: `Design generated: ${files.length} files at ${outputPath}`,
    timestamp: Date.now(),
  });

  return {
    current_project: {
      design_gen: {
        generated_at: Date.now(),
        file_count: files.length,
        output_path: outputPath,
      },
    } as ProjectItem,
    agent_events: [
      {
        agent: "design_generator" as const,
        phase: "execution" as const,
        status: "done" as const,
        message: `Generated ${files.length} design files`,
        timestamp: Date.now(),
      },
    ],
  };
}