import { describe, it, expect } from "vitest";
import { writeProjectFiles } from "./file-writer.js";

describe("FALLBACK_FILES", () => {
  it("are valid files that pass security validation", async () => {
    // FALLBACK_FILES is the set used when LLM returns empty
    // We test that all fallback files pass validation
    const fallbackFiles = [
      {
        path: "package.json",
        content: JSON.stringify({
          name: "generated-project",
          version: "1.0.0",
          scripts: { dev: "tsx watch src/index.ts", build: "tsc" },
          dependencies: {},
          devDependencies: { typescript: "^5.0.0", tsx: "^4.0.0" },
        }),
      },
      {
        path: "tsconfig.json",
        content: JSON.stringify({
          compilerOptions: { target: "ES2020", module: "ESNext", strict: true },
        }),
      },
      {
        path: "src/index.ts",
        content: "// Generated entry point\nconsole.log('Hello, World!');\n",
      },
      {
        path: "README.md",
        content: "# Generated Project\n\nGenerated by Happy-Agents AI.\n",
      },
    ];

    const result = await writeProjectFiles("fallback-test", fallbackFiles, "/tmp");
    expect(result.written).toHaveLength(4);
    expect(result.written).toContain("package.json");
    expect(result.written).toContain("tsconfig.json");
    expect(result.written).toContain("src/index.ts");
    expect(result.written).toContain("README.md");
  });
});
