import type { ProjectItem } from "../models";

function renderList(items: unknown[]): string {
  if (!items?.length) return "";
  return items.map((item) => {
    if (typeof item === "object" && item !== null) {
      return `- ${JSON.stringify(item)}`;
    }
    return `- ${String(item)}`;
  }).join("\n");
}

function section(emoji: string, title: string, body: string): string {
  return `## ${emoji} ${title}\n\n${body}\n\n`;
}

export function generatePRD(project: ProjectItem): string {
  const parts: string[] = [];

  parts.push(`# Product Requirements Document (PRD)\n\n`);
  parts.push(`**Project:** ${project.project_title}\n`);
  parts.push(`**Date:** ${new Date().toISOString().split("T")[0]}\n`);
  parts.push(`**Phase:** ${project.current_phase}\n`);
  parts.push(`**Priority:** ${project.ceo_decision.priority}\n`);
  parts.push(`**Status:** ${project.status}\n\n`);
  parts.push("---\n\n");

  if (project.project_description) {
    parts.push(section("📋", "Executive Summary", project.project_description));
  }

  parts.push(section("👔", "CEO Decision", [
    `**Accepted:** ${project.ceo_decision.accepted ? "Yes" : "No"}`,
    `**Priority:** ${project.ceo_decision.priority}`,
    `**Resource Allocation:** ${project.ceo_decision.resource_allocation}`,
    project.ceo_decision.reasoning ? `\n**Reasoning:** ${project.ceo_decision.reasoning}` : "",
  ].filter(Boolean).join("\n\n")));

  if (project.cto_output.architecture || project.cto_output.tech_stack?.length) {
    const ctoBody = [
      `### Architecture`,
      project.cto_output.architecture,
      ``,
      `### Tech Stack`,
      renderList(project.cto_output.tech_stack),
      ``,
      `### System Design`,
      project.cto_output.system_design,
      ``,
      `### Technical Risks`,
      renderList(project.cto_output.technical_risks),
    ].join("\n");
    parts.push(section("🏗️", "CTO — Architecture & Tech Stack", ctoBody));
  }

  if (project.product_owner_output.user_stories?.length || project.product_owner_output.backlog?.length) {
    const poBody = [
      `### User Stories`,
      ...(project.product_owner_output.user_stories ?? []).map((us, i) =>
        `${i + 1}. **As a** ${us.as} — **want** ${us.want} — **so that** ${us.so}\n   Acceptance: ${(us.acceptance ?? []).join(", ") || "none"}`
      ),
      ``,
      `### Backlog`,
      renderList(project.product_owner_output.backlog),
      ``,
      `### Sprint Plan`,
      project.product_owner_output.sprint_plan,
    ].join("\n");
    parts.push(section("📦", "Product Owner — User Stories & Backlog", poBody));
  }

  if (project.product_manager_output.strategy || project.product_manager_output.roadmap?.length) {
    const pmBody = [
      `### Strategy`,
      project.product_manager_output.strategy,
      ``,
      `### Roadmap`,
      renderList(project.product_manager_output.roadmap),
      ``,
      `### Feature Priority`,
      renderList(project.product_manager_output.feature_priority),
      ``,
      `### Competitive Analysis`,
      project.product_manager_output.competitive_analysis,
    ].join("\n");
    parts.push(section("🎯", "Product Manager — Strategy & Roadmap", pmBody));
  }

  if (project.business_marketing_output.market_analysis || project.business_marketing_output.go_to_market?.length) {
    const bmBody = [
      `### Market Analysis`,
      project.business_marketing_output.market_analysis,
      ``,
      `### Go-to-Market`,
      renderList(project.business_marketing_output.go_to_market),
      ``,
      `### Pricing Strategy`,
      project.business_marketing_output.pricing_strategy,
      ``,
      `### KPIs`,
      renderList(project.business_marketing_output.kpis),
    ].join("\n");
    parts.push(section("📈", "Business & Marketing", bmBody));
  }

  parts.push("---\n");
  parts.push(`*Generated by A-Company AI Agent System*\n`);

  return parts.join("");
}

export function generateTRD(project: ProjectItem): string {
  const parts: string[] = [];

  parts.push(`# Technical Requirements Document (TRD)\n\n`);
  parts.push(`**Project:** ${project.project_title}\n`);
  parts.push(`**Date:** ${new Date().toISOString().split("T")[0]}\n`);
  parts.push(`**Phase:** ${project.current_phase}\n\n`);
  parts.push("---\n\n");

  if (project.cto_output.architecture || project.cto_output.tech_stack?.length) {
    const ctoBody = [
      `### Architecture`,
      project.cto_output.architecture,
      ``,
      `### Tech Stack`,
      renderList(project.cto_output.tech_stack),
      ``,
      `### System Design`,
      project.cto_output.system_design,
      ``,
      `### Technical Risks`,
      renderList(project.cto_output.technical_risks),
    ].join("\n");
    parts.push(section("🏗️", "CTO — Architecture & Technical Decisions", ctoBody));
  }

  if (project.engineer_output.implementation_plan?.length || project.engineer_output.code_structure) {
    const engBody = [
      `### Implementation Plan`,
      renderList(project.engineer_output.implementation_plan),
      ``,
      `### Code Structure`,
      project.engineer_output.code_structure,
      ``,
      `### Estimates`,
      project.engineer_output.estimates
        ? Object.entries(project.engineer_output.estimates).map(([k, v]) => `- **${k}:** ${v}`).join("\n")
        : "",
      ``,
      `### Dependencies`,
      renderList(project.engineer_output.dependencies),
    ].join("\n");
    parts.push(section("⚙️", "Engineer — Implementation Plan", engBody));
  }

  if (project.designer_output.wireframes?.length || project.designer_output.design_system) {
    const desBody = [
      `### Wireframes`,
      renderList(project.designer_output.wireframes),
      ``,
      `### Design System`,
      project.designer_output.design_system,
      ``,
      `### UX Flows`,
      renderList(project.designer_output.ux_flows),
      ``,
      `### Deliverables`,
      renderList(project.designer_output.deliverables),
    ].join("\n");
    parts.push(section("🎨", "Designer — UI/UX Deliverables", desBody));
  }

  if (project.qa_output.test_plan || project.qa_output.test_cases?.length) {
    const testCasesStr = (project.qa_output.test_cases ?? []).map((tc, i) => {
      const steps = Array.isArray(tc.steps) ? tc.steps.join(" → ") : String(tc.steps ?? "");
      return `${i + 1}. **${String(tc.name ?? "")}** (${String(tc.type ?? "")})\n   Steps: ${steps}`;
    }).join("\n\n");
    const qaBody = [
      `### Test Plan`,
      project.qa_output.test_plan,
      ``,
      `### Test Cases`,
      testCasesStr,
      ``,
      `### Quality Gates`,
      renderList(project.qa_output.quality_gates),
      ``,
      `### Bug Risks`,
      renderList(project.qa_output.bug_risks),
    ].join("\n");
    parts.push(section("🧪", "QA — Test Plan & Quality Gates", qaBody));
  }

  parts.push("---\n");
  parts.push(`*Generated by A-Company AI Agent System*\n`);

  return parts.join("");
}